version: '2'
services:
  user-service:
    image: gramman75/user-service:1.0
    container_name: user-service
    environment:
      spring.rabbitmq.host: rabbitmq
      spring.datasource.url: jdbc:mariadb://mariadb:3306/userdb
      spring.datasource.username: root
      spring.datasource.password: mariadb
      spring.jpa.hibernate.ddl-auto: update
      spring.zipkin.base-url: http://zipkin:9411
      spring.cloud.config.uri: http://config-service:8888
      eureka.client.service-url.defaultZone: http://discovery-service:8761/eureka

    networks:
      - my-network
networks:
  my-network:
    name: ecommerce-network