spring:
  profiles:
    active: @activatedProperties@
  application:
    name: user-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
greeting:
  message: Welcome to the E-Commerce

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: health, refresh, beans, busrefresh, info, prometheus, metrics
#token:
#  expiration_time : 1000000
#  secret: user_name

order_service:
  url: http://localhost:8000/order-service/%s/order

logging:
  level:
    com.example.userservice.client: DEBUG