server:
  port: 0

spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/C:\data\user-service # jdbc:h2:file:C:\data\test
    url: jdbc:mariadb://localhost:3306/userdb
    dirver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: mariadb
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
  jpa:
    hibernate:
      ddl-auto: update
      naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        jdbc:
          lob:
            non_contextual_creation: true
        show_sql: true
        format_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id:  ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
logging:
  level:
    com.example.userservice.client: DEBUG